# Generated by Django 6.0.4 on 2026-04-12 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='candidate',
            unique_together={('job', 'file_hash')},
        ),
    ]
