# Generated by Django 6.0.4 on 2026-04-13 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0002_alter_candidate_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='github',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='portfolio',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='file_hash',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='status',
            field=models.CharField(choices=[('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('UNDER_REVIEW', 'Under Review'), ('UNSCREENED', 'Unscreened')], default='UNSCREENED', max_length=20),
        ),
    ]
