# Generated by Django 6.0.4 on 2026-04-13 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0003_candidate_github_candidate_portfolio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='candidate_status',
            field=models.CharField(choices=[('unscreened', 'Unscreened'), ('screening', 'Screening'), ('shortlisted', 'Shortlisted'), ('rejected', 'Rejected')], default='unscreened', max_length=50),
        ),
    ]
