# Generated by Django 6.0.4 on 2026-04-13 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0004_candidate_candidate_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='candidate_status',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='twitter',
        ),
        migrations.AddField(
            model_name='candidate',
            name='demonstrated_skills',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='candidate',
            name='extracted_skills',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='candidate',
            name='gaps',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='candidate',
            name='is_screened',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='candidate',
            name='listed_skills_only',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='candidate',
            name='recommendation',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='candidate',
            name='strengths',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='experience',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='match_score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='status',
            field=models.CharField(choices=[('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('UNDER_REVIEW', 'Under Review'), ('NOT_SCREENED', 'Not Screened')], default='NOT_SCREENED', max_length=20),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='summary',
            field=models.TextField(blank=True),
        ),
    ]
