# Generated by Django 6.0.4 on 2026-04-23 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0006_job_jd_file_job_jd_text_alter_job_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.CharField(default='individual', max_length=20),
        ),
        migrations.AddField(
            model_name='job',
            name='query',
            field=models.TextField(default=''),
        ),
    ]
