# Generated by Django 6.0.4 on 2026-04-09 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0002_job_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='job_id',
        ),
    ]
